"""Rotor and Reflector wirings

	Rotor I, II, III - introduced with first military Enigma machines in 1930
	Rotor IV, V - introduced with model M3 for the Army in December 1938

	As stated in the readme, these wirings are taken from "https://en.wikipedia.org/wiki/Enigma_rotor_details#Rotor_wiring_tables"
"""

rotorI = { 'A':'E',
		   'B':'K',
		   'C':'M',
		   'D':'F',
		   'E':'L',
		   'F':'G',
		   'G':'D',
		   'H':'Q',
		   'I':'V',
		   'J':'Z',
		   'K':'N',
		   'L':'T',
		   'M':'O',
		   'N':'W',
		   'O':'Y',
		   'P':'H',
		   'Q':'X',
		   'R':'U',
		   'S':'S',
		   'T':'P',
		   'U':'A',
		   'V':'I',
		   'W':'B',
		   'X':'R',
		   'Y':'C',
		   'Z':'J' }
notchI = 'Q'

rotorII = { 'A':'A',
		    'B':'J',
		    'C':'D',
		    'D':'K',
		    'E':'S',
		    'F':'I',
		    'G':'R',
		    'H':'U',
		    'I':'X',
		    'J':'B',
		    'K':'L',
		    'L':'H',
		    'M':'W',
		    'N':'T',
		    'O':'M',
		    'P':'C',
		    'Q':'Q',
		    'R':'G',
		    'S':'Z',
		    'T':'N',
		    'U':'P',
		    'V':'Y',
		    'W':'F',
		    'X':'V',
		    'Y':'O',
		    'Z':'E' }
notchII = 'E'

rotorIII = { 'A':'B',
		     'B':'D',
		     'C':'F',
		     'D':'H',
		     'E':'J',
		     'F':'L',
		     'G':'C',
		     'H':'P',
		     'I':'R',
		     'J':'T',
		     'K':'X',
		     'L':'V',
		     'M':'Z',
		     'N':'N',
		     'O':'Y',
		     'P':'E',
		     'Q':'I',
		     'R':'W',
		     'S':'G',
		     'T':'A',
		     'U':'K',
		     'V':'M',
		     'W':'U',
		     'X':'S',
		     'Y':'Q',
		     'Z':'O' }
notchIII = 'V'

rotorIV = { 'A':'E',
		    'B':'S',
		    'C':'O',
		    'D':'V',
		    'E':'P',
		    'F':'Z',
		    'G':'J',
		    'H':'A',
		    'I':'Y',
		    'J':'Q',
		    'K':'U',
		    'L':'I',
		    'M':'R',
		    'N':'H',
		    'O':'X',
		    'P':'L',
		    'Q':'N',
		    'R':'F',
		    'S':'T',
		    'T':'G',
		    'U':'K',
		    'V':'D',
		    'W':'C',
		    'X':'M',
		    'Y':'W',
		    'Z':'B' }
notchIV = 'J'

rotorV = { 'A':'V',
		   'B':'Z',
		   'C':'B',
		   'D':'R',
		   'E':'G',
		   'F':'I',
		   'G':'T',
		   'H':'Y',
		   'I':'U',
		   'J':'P',
		   'K':'S',
		   'L':'D',
		   'M':'N',
		   'N':'H',
		   'O':'L',
		   'P':'X',
		   'Q':'A',
		   'R':'W',
		   'S':'M',
		   'T':'J',
		   'U':'Q',
		   'V':'O',
		   'W':'F',
		   'X':'E',
		   'Y':'C',
		   'Z':'K' }
notchV = 'Z'

#reflector 'pin 1' (topmost pin) is actually B and not A, according to:
#https://www.cryptomuseum.com/crypto/enigma/wiring.htm
reflectorA = { 'A':'E',
			   'B':'J',
			   'C':'M',
			   'D':'Z',
			   'E':'A',
			   'F':'L',
			   'G':'Y',
			   'H':'X',
			   'I':'V',
			   'J':'B',
			   'K':'W',
			   'L':'F',
			   'M':'C',
			   'N':'R',
			   'O':'Q',
			   'P':'U',
			   'Q':'O',
			   'R':'N',
			   'S':'T',
			   'T':'S',
			   'U':'P',
			   'V':'I',
			   'W':'K',
			   'X':'H',
			   'Y':'G',
			   'Z':'D' }

reflectorB = { 'A':'Y',
			   'B':'R',
			   'C':'U',
			   'D':'H',
			   'E':'Q',
			   'F':'S',
			   'G':'L',
			   'H':'D',
			   'I':'P',
			   'J':'X',
			   'K':'N',
			   'L':'G',
			   'M':'O',
			   'N':'K',
			   'O':'M',
			   'P':'I',
			   'Q':'E',
			   'R':'B',
			   'S':'F',
			   'T':'Z',
			   'U':'C',
			   'V':'W',
			   'W':'V',
			   'X':'J',
			   'Y':'A',
			   'Z':'T' }

reflectorC = { 'A':'F',
			   'B':'V',
			   'C':'P',
			   'D':'J',
			   'E':'I',
			   'F':'A',
			   'G':'O',
			   'H':'Y',
			   'I':'E',
			   'J':'D',
			   'K':'R',
			   'L':'Z',
			   'M':'X',
			   'N':'W',
			   'O':'G',
			   'P':'C',
			   'Q':'T',
			   'R':'K',
			   'S':'U',
			   'T':'Q',
			   'U':'S',
			   'V':'B',
			   'W':'N',
			   'X':'M',
			   'Y':'H',
			   'Z':'L' }