"""Rotor and Reflector wirings

	Rotor I, II, III - introduced with first military Enigma machines in 1930
	Rotor IV, V - introduced with model M3 for the Army in December 1938

	As stated in the readme, these wirings are taken from "https://en.wikipedia.org/wiki/Enigma_rotor_details#Rotor_wiring_tables"
"""

rotorI = { 'a':'e',
		   'b':'k',
		   'c':'m',
		   'd':'f',
		   'e':'l',
		   'f':'g',
		   'g':'d',
		   'h':'q',
		   'i':'v',
		   'j':'z',
		   'k':'n',
		   'l':'t',
		   'm':'o',
		   'n':'w',
		   'o':'y',
		   'p':'h',
		   'q':'x',
		   'r':'u',
		   's':'s',
		   't':'p',
		   'u':'a',
		   'v':'i',
		   'w':'b',
		   'x':'r',
		   'y':'c',
		   'z':'j' }
notchI = 'q'

rotorII = { 'a':'a',
		    'b':'j',
		    'c':'d',
		    'd':'k',
		    'e':'s',
		    'f':'i',
		    'g':'r',
		    'h':'u',
		    'i':'x',
		    'j':'b',
		    'k':'l',
		    'l':'h',
		    'm':'w',
		    'n':'t',
		    'o':'m',
		    'p':'c',
		    'q':'q',
		    'r':'g',
		    's':'z',
		    't':'n',
		    'u':'p',
		    'v':'y',
		    'w':'f',
		    'x':'v',
		    'y':'o',
		    'z':'e' }
notchII = 'e'

rotorIII = { 'a':'b',
		     'b':'d',
		     'c':'f',
		     'd':'h',
		     'e':'j',
		     'f':'l',
		     'g':'c',
		     'h':'p',
		     'i':'r',
		     'j':'t',
		     'k':'x',
		     'l':'v',
		     'm':'z',
		     'n':'n',
		     'o':'y',
		     'p':'e',
		     'q':'i',
		     'r':'w',
		     's':'g',
		     't':'a',
		     'u':'k',
		     'v':'m',
		     'w':'u',
		     'x':'s',
		     'y':'q',
		     'z':'o' }
notchIII = 'v'

rotorIV = { 'a':'e',
		    'b':'s',
		    'c':'o',
		    'd':'v',
		    'e':'p',
		    'f':'z',
		    'g':'j',
		    'h':'a',
		    'i':'y',
		    'j':'q',
		    'k':'u',
		    'l':'i',
		    'm':'r',
		    'n':'h',
		    'o':'x',
		    'p':'l',
		    'q':'n',
		    'r':'f',
		    's':'t',
		    't':'g',
		    'u':'k',
		    'v':'d',
		    'w':'c',
		    'x':'m',
		    'y':'w',
		    'z':'b' }
notchIV = 'j'

rotorV = { 'a':'v',
		   'b':'z',
		   'c':'b',
		   'd':'r',
		   'e':'g',
		   'f':'i',
		   'g':'t',
		   'h':'y',
		   'i':'u',
		   'j':'p',
		   'k':'s',
		   'l':'d',
		   'm':'n',
		   'n':'h',
		   'o':'l',
		   'p':'x',
		   'q':'a',
		   'r':'w',
		   's':'m',
		   't':'j',
		   'u':'q',
		   'v':'o',
		   'w':'f',
		   'x':'e',
		   'y':'c',
		   'z':'k' }
notchV = 'z'

reflectorA = { 'a':'e',
			   'b':'j',
			   'c':'m',
			   'd':'z',
			   'e':'a',
			   'f':'l',
			   'g':'y',
			   'h':'x',
			   'i':'v',
			   'j':'b',
			   'k':'w',
			   'l':'f',
			   'm':'c',
			   'n':'r',
			   'o':'q',
			   'p':'u',
			   'q':'o',
			   'r':'n',
			   's':'t',
			   't':'s',
			   'u':'p',
			   'v':'i',
			   'w':'k',
			   'x':'h',
			   'y':'g',
			   'z':'d' }

reflectorB = { 'a':'y',
			   'b':'r',
			   'c':'u',
			   'd':'h',
			   'e':'q',
			   'f':'s',
			   'g':'l',
			   'h':'d',
			   'i':'p',
			   'j':'x',
			   'k':'n',
			   'l':'g',
			   'm':'o',
			   'n':'k',
			   'o':'m',
			   'p':'i',
			   'q':'e',
			   'r':'b',
			   's':'f',
			   't':'z',
			   'u':'c',
			   'v':'w',
			   'w':'v',
			   'x':'j',
			   'y':'a',
			   'z':'t' }

reflectorC = { 'a':'f',
			   'b':'v',
			   'c':'p',
			   'd':'j',
			   'e':'i',
			   'f':'a',
			   'g':'o',
			   'h':'y',
			   'i':'e',
			   'j':'d',
			   'k':'r',
			   'l':'z',
			   'm':'x',
			   'n':'w',
			   'o':'g',
			   'p':'c',
			   'q':'t',
			   'r':'k',
			   's':'u',
			   't':'q',
			   'u':'s',
			   'v':'b',
			   'w':'n',
			   'x':'m',
			   'y':'h',
			   'z':'l' }